// References:
// useNavigate: https://reactrouter.com/en/main/hooks/use-navigate
// useParams: https://reactrouter.com/en/main/hooks/use-params
// FormData: https://developer.mozilla.org/en-US/docs/Web/API/FormData
// URL.createObjectURL (Preview Images): https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL
// Vite Environment Variables: https://vitejs.dev/guide/env-and-mode.html


import { useEffect, useState } from "react";
import { getAnimalById } from "../api/animals";
import { updateAnimal } from "../api/animals";
import styles from "./AdminAnimalCreate.module.css"; // reuse same styles from animal create page
import { useNavigate, useParams } from "react-router-dom";

export default function AdminAnimalUpdate() {
  const navigate = useNavigate();
  const { animalId } = useParams(); // extract animalId from URL

  // Form state for editable fields
  const [form, setForm] = useState({
    name: "",
    species: "",
    breed: "",
    age: "",
    gender: "",
    description: "",
    adoption_status: "",
  });

  const [currentImage, setCurrentImage] = useState(null); // existing image from DB
  const [newImage, setNewImage] = useState(null); // new uploaded image
  const [preview, setPreview] = useState(null); // preview new image
  const [error, setError] = useState("");

  // Load base API URL from environment variables
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Load existing animal when page opens
  useEffect(() => {
    async function load() {
      const animal = await getAnimalById(animalId);

      // pre fill form using existing values
      setForm({
        name: animal.name,
        species: animal.species,
        breed: animal.breed,
        age: animal.age,
        gender: animal.gender,
        description: animal.description,
        adoption_status: animal.adoption_status,
      });

      // Store current image URL
      setCurrentImage(animal.photo_url);
    }

    load();
  }, [animalId]);

  // handler for updating input fields
  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  // When selecting new image, store file and create preview
  const handleImage = (e) => {
    const file = e.target.files[0];
    setNewImage(file);
    setPreview(URL.createObjectURL(file));
  };

  // Submit updated animal
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    try {
      // Use multipart/form-data to match backend
      const fd = new FormData();

      // Prepare JSON part for request_data field
      const jsonData = {
        name: form.name,
        species: form.species,
        breed: form.breed,
        age: Number(form.age),
        gender: form.gender,
        description: form.description,
        adoption_status: form.adoption_status,
      };

      fd.append("request_data", JSON.stringify(jsonData));

      // Only append image if user selected new one
      if (newImage) {
        fd.append("animal_image", newImage);
      }

      await updateAnimal(animalId, fd);

      alert("Animal updated successfully!");
      navigate("/admin/animals"); // redirect back to animal list

    } catch (err) {
      console.error(err);
      setError(err.response?.data?.detail || "Failed to update animal.");
    }
  };

  // UI Rendering
  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <div className={styles.innerBox}>

        <h2 className={styles.title}>Update Animal</h2>

        <form className={styles.form} onSubmit={handleSubmit}>
          
          <label>Name</label>
          <input name="name" value={form.name} onChange={handleChange} required />

          <label>Species</label>
          <input name="species" value={form.species} onChange={handleChange} required />

          <label>Breed</label>
          <input name="breed" value={form.breed} onChange={handleChange} required />

          <label>Age</label>
          <input 
            type="number"
            name="age"
            value={form.age}
            onChange={handleChange}
            required
          />

          <label>Gender</label>
          <select name="gender" value={form.gender} onChange={handleChange} required>
            <option value="">Select gender</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
          </select>

          <label>Status</label>
          <select
            name="adoption_status"
            value={form.adoption_status}
            onChange={handleChange}
          >
            <option value="Available">Available</option>
            <option value="Adopted">Adopted</option>
          </select>

          <label>Description</label>
          <textarea
            name="description"
            value={form.description}
            onChange={handleChange}
            rows="4"
          />

          {/* Existing Image */}
          <label>Current Image</label>
          {currentImage ? (
            <img
              src={`${BASE_URL}${currentImage}`}
              alt="current animal"
              className={styles.preview}
            />
          ) : (
            <p>No image available</p>
          )}

          {/* Upload new image */}
          <label>Change Image (optional)</label>
          <input 
            type="file"
            accept="image/*"
            onChange={handleImage}
          />

          {/* New image preview */}
          {preview && (
            <>
              <p>New Image Preview:</p>
              <img src={preview} className={styles.preview} />
            </>
          )}

          {error && <p className={styles.error}>{error}</p>}

          {/* Buttons */}
          <div className={styles.buttonRow}>
            <button className={styles.saveBtn}>Update Animal</button>

            <button 
              type="button"
              className={styles.cancelBtn}
              onClick={() => navigate("/admin/animals")}
            >
              Cancel
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
