// References:
// https://www.freecodecamp.org/news/how-to-build-forms-in-react/
// https://www.w3schools.com/react/react_forms_multiple_inputs.asp

import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getCurrentUser, updateAdmin } from "../api/users";
import styles from "../styles/AdminProfile.module.css";

export default function AdminProfile() {

  const navigate = useNavigate();

  // Store original data to detect unsaved changes
  const [original, setOriginal] = useState(null);

  // Form state
  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    password: "",
    confirmPassword: ""
  });

  // current admin ID
  const [userId, setUserId] = useState(null);

  // Track changes (true = enable Save button)
  const [isDirty, setIsDirty] = useState(false);

  // Password mismatch error
  const [passwordError, setPasswordError] = useState("");

  // Load the current admin's data
  useEffect(() => {
    async function loadAdmin() {
      const user = await getCurrentUser();

      setUserId(user.id);

      const initial = {
        name: user.name || "",
        email: user.email || "",
        phone: user.phone || "",
        address: user.address || "",
      };

      // Save original data
      setOriginal(initial);

      // Set form fields
      setForm({
        ...initial,
        password: "",
        confirmPassword: ""
      });
    }

    loadAdmin(); // trigger async function
  }, []);

  // Detect if any form field has changed compared to original
  useEffect(() => {
    if (!original) return;

    const hasChanges =
      form.name !== original.name ||
      form.email !== original.email ||
      form.phone !== original.phone ||
      form.address !== original.address ||
      form.password.length > 0 ||
      form.confirmPassword.length > 0;

    setIsDirty(hasChanges);
  }, [form, original]);


   // Update form state when typing
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };


  const handleCancel = () => {
    navigate("/admin/dashboard");
  };

  // Submit profile update & redirect to logout
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate password confirmation
    if (form.password !== form.confirmPassword) {
      setPasswordError("Passwords do not match");
      return;
    }

    setPasswordError("");

    // Build request payload
    const payload = {
      name: form.name,
      email: form.email,
      phone: form.phone,
      address: form.address,
    };

    // Only send password if provided
    if (form.password) {
      payload.password = form.password;
    }

    // Send API request to update admin profile
    await updateAdmin(userId, payload);

    alert("Profile updated. Please log in again.");

    // logout
    localStorage.removeItem("adminToken");
    navigate("/admin/login", { replace: true });
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <div className={styles.innerBox}>
        <h2 className={styles.title}>Admin Profile</h2>

        <form className={styles.form} onSubmit={handleSubmit}>
          
          {/* Name */}
          <label>Name</label>
          <input
            type="text"
            name="name"
            value={form.name}
            onChange={handleChange}
          />

          {/* Email */}
          <label>Email</label>
          <input
            type="email"
            name="email"
            value={form.email}
            onChange={handleChange}
          />

          {/* Phone */}
          <label>Phone</label>
          <input
            type="text"
            name="phone"
            value={form.phone}
            onChange={handleChange}
          />

          {/* Address */}
          <label>Address</label>
          <input
            type="text"
            name="address"
            value={form.address}
            onChange={handleChange}
          />

          {/* Password */}
          <label>New Password (optional)</label>
          <input
            type="password"
            name="password"
            value={form.password}
            onChange={handleChange}
            placeholder="Enter new password"
          />

          {/* Confirm Password */}
          <label>Confirm New Password</label>
          <input
            type="password"
            name="confirmPassword"
            value={form.confirmPassword}
            onChange={handleChange}
            placeholder="Re-enter new password"
          />

          {/* Show password mismatch error */}
          {passwordError && <p className={styles.error}>{passwordError}</p>}

          {/* Action buttons */}
          <div className={styles.btnRow}>
            <button
              type="button"
              className={styles.cancelBtn}
              onClick={handleCancel}
            >
              Cancel
            </button>

            <button
              type="submit"
              className={styles.saveBtn}
              disabled={!isDirty}
            >
              Save Changes
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
