// References:
// https://www.w3schools.com/jsref/met_win_settimeout.asp
// https://www.w3schools.com/react/react_useeffect.asp
// https://www.w3schools.com/jsref/jsref_filter.asp
// https://www.telerik.com/blogs/how-to-create-custom-debounce-hook-react
// Implementing CSV Data Export in React: https://dev.to/graciesharma/implementing-csv-data-export-in-react-without-external-libraries-3030
// Creating & Downloading Files Using Blob: https://developer.mozilla.org/en-US/docs/Web/API/Blob
// Creating Downloadable URLs: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static
// Triggering File Download: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#attr-download,https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click


import { useEffect, useState } from "react";
import { getAnimals } from "../api/animals";
import styles from "./AdminAnimals.module.css";
import { useNavigate } from "react-router-dom";
import { deleteAnimal } from "../api/animals";

export default function AdminAnimals() {
  const navigate = useNavigate();

  // Data states
  const [animals, setAnimals] = useState([]);

  // Pagination states
  const [page, setPage] = useState(1);
  const [limit] = useState(10);
  const [totalPages, setTotalPages] = useState(1);

  // Filters
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [gender, setGender] = useState("");
  const [status, setStatus] = useState("");

  // Load API base URL from .env
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Debounce for search input
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1); // reset to page 1 when typing new search
    }, 500);

    return () => clearTimeout(timer);
  }, [search]);

  // Load animals from API
  const loadAnimals = async () => {
    try {
      const res = await getAnimals(page, limit, debouncedSearch, gender, status);

      const payload = res.data ?? res;
      const data = payload.data ?? payload;

      setAnimals(data.animals || []);
      setTotalPages(data.total_pages || 1);
    } catch (err) {
      console.error("Failed to load animals", err);
      setAnimals([]);
      setTotalPages(1);
    }
  };

  // Reload animals when something changes
  useEffect(() => {
    loadAnimals();
  }, [page, debouncedSearch, gender, status]);


  // Clear all filters
  const clearFilters = () => {
    setSearch("");
    setDebouncedSearch("");
    setGender("");
    setStatus("");
    setPage(1);
  };

  // Status color badge
  const statusClass = (s) => {
    if (!s) return styles.statusUnknown;
    const key = String(s).toLowerCase();
    if (key === "available") return styles.statusAvailable;
    if (key === "adopted") return styles.statusAdopted;
    return styles.statusUnknown;
  };

  // Export current list to CSV
  const handleExport = () => {
    if (!animals || animals.length === 0) {
      alert("No animals to export.");
      return;
    }

    // Build CSV header and rows
    const headers = [
      "ID",
      "Name",
      "Species",
      "Breed",
      "Age",
      "Gender",
      "Status",
      "Description",
      "Created At",
      "Updated At"
    ];

    const rows = animals.map((a) => [
      a.id,
      a.name,
      a.species,
      a.breed,
      a.age,
      a.gender,
      a.adoption_status,
      a.description,
      new Date(a.created_at).toLocaleString(),
      new Date(a.updated_at).toLocaleString()
    ]);

    // Convert the data array into a CSV string
    const csvContent =
      [headers, ...rows].map((row) =>
        row
          .map((cell) => {
            if (cell == null) return "";
            return `"${String(cell).replaceAll('"', "'")}"`;
          })
          .join(",")
      )
      .join("\r\n");

    // Create blob and download
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const ts = new Date().toISOString().slice(0, 10);
    const filename = `animals-export-${ts}.csv`;

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Handle delete animal
  const handleDelete = async (animalId) => {
    const yes = confirm("Are you sure?");
    if (!yes) return;

    try {
      await deleteAnimal(animalId);
      alert("Animal deleted successfully!");
      loadAnimals();
    } catch (err) {
      alert("Failed to delete", err);
    }
  };


  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>Animals Management</h2>

      {/* Search + Filters */}
      <div className={styles.filters}>
        {/* Search box */}
        <input
          type="text"
          placeholder="Search name, species, breed..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />

        {/* Gender filter */}
        <select value={gender} onChange={(e) => {
          setGender(e.target.value);
          setPage(1);
        }}>
          <option value="">All Genders</option>
          <option value="Male">Male</option>
          <option value="Female">Female</option>
        </select>

        {/* Status filter */}
        <select value={status} onChange={(e) => {
          setStatus(e.target.value);
          setPage(1);
        }}>
          <option value="">All Status</option>
          <option value="Available">Available</option>
          <option value="Adopted">Adopted</option>
        </select>

        {/* Clear Filters */}
        <button className={styles.clearBtn} onClick={clearFilters}>
          Clear Filters
        </button>

        {/* Export Button */}
        <button
            type="button"
            className={styles.exportBtn}
            onClick={handleExport}
        >
            Export
        </button>

        {/* Add New Animal */}
        <button
          type="button"
          className={styles.addBtn}
          onClick={() => navigate("/admin/animals/create")}
        >
          + Add New Animal
        </button>
      </div>

      {/* Animals Table */}
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Photo</th>
            <th>Name</th>
            <th>Species</th>
            <th>Breed</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          {animals.map((a) => (
            <tr key={a.id}>
              {/* Photo */}
              <td>
                {a.photo_url ? (
                  <img src={`${BASE_URL}${a.photo_url}`} alt={a.name} className={styles.photo} />
                ) : (
                  <div className={styles.noImage}>No Image</div>
                )}
              </td>

              <td>{a.name}</td>
              <td>{a.species}</td>
              <td>{a.breed}</td>
              <td>{a.age}</td>
              <td>{a.gender}</td>

              <td>
                <span
                  className={`${styles.statusBadge} ${statusClass(a.adoption_status)}`}
                >
                  {a.adoption_status}
                </span>
              </td>

              <td>{a.created_at ? new Date(a.created_at).toLocaleDateString() : ""}</td>
              <td>{a.updated_at ? new Date(a.updated_at).toLocaleDateString() : ""}</td>

              <td className={styles.actions}>
                <button
                  className={styles.updateBtn}
                  onClick={() => navigate(`/admin/animals/update/${a.id}`)}
                >
                  Update
                </button>

                <button className={styles.deleteBtn} onClick={() => handleDelete(a.id)}>
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Pagination  */}
      <div className={styles.pagination}>
        <button disabled={page === 1} onClick={() => setPage(page - 1)}>
          Prev
        </button>

        <span>Page {page} of {totalPages}</span>

        <button disabled={page === totalPages} onClick={() => setPage(page + 1)}>
          Next
        </button>
      </div>
    </div>
  );
}
