// References:
// React useState: https://react.dev/reference/react/useState
// React useEffect: https://react.dev/reference/react/useEffect


import { useEffect, useState } from "react";
import { getAdminUsers } from "../api/users";
import styles from "./AdminUsers.module.css";

export default function AdminUsers() {

  // Store list of admin users
  const [admins, setAdmins] = useState([]);

  // Pagination states
  const [page, setPage] = useState(1);
  const [limit] = useState(10);
  const [totalPages, setTotalPages] = useState(1);

  // Search input state
  const [searchInput, setSearchInput] = useState("");

  // Debounced search
  const [debouncedSearch, setDebouncedSearch] = useState("");

  // Debounce search input
  // Prevents API being called on every keystroke
  useEffect(() => {
    const t = setTimeout(() => {
      setDebouncedSearch(searchInput);
      setPage(1); // reset to first page on filter
    }, 500);

    return () => clearTimeout(t);
  }, [searchInput]);

  // Load admins when page or search filters change
  useEffect(() => {
    loadAdmins();
  }, [page, debouncedSearch]);

  // Fetch admin list from backend
  async function loadAdmins() {
    try {
      const params = {
        page,
        limit,
        search: debouncedSearch || undefined,
      };

      const data = await getAdminUsers(params);
      setAdmins(data.users || []);
      setTotalPages(data.total_pages || 1);

    } catch (err) {
      console.error("Failed to load admins:", err);
    }
  }

  // Clear all filters and reset list
  const clearFilters = () => {
    setSearchInput("");
    setDebouncedSearch("");
    setPage(1);
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>Admin Management</h2>

      {/* FILTERS SECTION */}
      <div className={styles.filters}>
        {/* Search input */}
        <input
          type="text"
          placeholder="Search by name, email or address"
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
        />

        {/* Clear Filters button */}
        <button className={styles.clearBtn} onClick={clearFilters}>
          Clear Filters
        </button>

        {/* Create new admin */}
        <button
          className={styles.createBtn}
        >
          + Create Admin
        </button>
      </div>

      {/* TABLE SECTION */}
      <div className={styles.tableWrapper}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Joined At</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {admins.map((u) => (
              <tr key={u.id}>
                <td>{u.name}</td>
                <td>{u.email}</td>
                <td>{u.phone}</td>
                <td>{u.address}</td>
                <td>{new Date(u.created_at).toLocaleDateString()}</td>

                <td className={styles.actions}>
                  {/* Update Admin */}
                  <button
                    className={styles.updateBtn}
                  >
                    Update
                  </button>

                  {/* Delete Admin */}
                  <button
                    className={styles.deleteBtn}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* PAGINATION SECTION */}
      <div className={styles.pagination}>
        {/* Previous Page */}
        <button
          disabled={page === 1}
          onClick={() => setPage(page - 1)}
        >
          Prev
        </button>

        {/* Current page indicator */}
        <span>Page {page} of {totalPages}</span>

        {/* Next page */}
        <button
          disabled={page === totalPages}
          onClick={() => setPage(page + 1)}
        >
          Next
        </button>
      </div>
    </div>
  );
}

