// References:
// https://react.dev/reference/react/useState
// https://react.dev/reference/react/useEffect
// https://react.dev/learn/sharing-state-between-components#controlled-components


import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createAdmin } from "../api/users";
import styles from "./AdminUserCreate.module.css";

export default function AdminUserCreate() {
  const navigate = useNavigate();

  // Local state for form inputs
  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    password: "",
    confirmPassword: ""
  });

  // Error message for validation or API error
  const [error, setError] = useState("");

  // Update form state whenever an input changes
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value, // dynamic key update
    });
  };

  // Cancel button
  const handleCancel = () => {
    navigate("/admin/users");
  };

  // Submit form
  const handleSubmit = async (e) => {
    e.preventDefault();  // prevent page reload
    setError("");

    // Validate password match
    if (form.password !== form.confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    // Prepare object to send to backend
    const payload = {
      name: form.name,
      email: form.email,
      phone: form.phone,
      address: form.address,
      password: form.password,
    };

    try {
      // Send POST request to backend
      await createAdmin(payload);

      alert("Admin account created successfully!");

      // Redirect
      navigate("/admin/users");
    } catch (err) {
      console.error(err);
      
      setError(err.response?.data?.detail || "Failed to create admin.");
    }
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <div className={styles.innerBox}>

        {/* Page Title */}
        <h2 className={styles.title}>Create Admin</h2>

        {/* Admin Creation Form */}
        <form className={styles.form} onSubmit={handleSubmit}>

          {/* Name Field */}
          <label>Name</label>
          <input
            type="text"
            name="name"
            value={form.name}
            onChange={handleChange}
            required
          />

          {/* Email Field */}
          <label>Email</label>
          <input
            type="email"
            name="email"
            value={form.email}
            onChange={handleChange}
            required
          />

          {/* Phone Field */}
          <label>Phone</label>
          <input
            type="text"
            name="phone"
            value={form.phone}
            onChange={handleChange}
            required
          />

          {/* Address Field */}
          <label>Address</label>
          <input
            type="text"
            name="address"
            value={form.address}
            onChange={handleChange}
            required
          />

          {/* Password Field */}
          <label>Password</label>
          <input
            type="password"
            name="password"
            value={form.password}
            onChange={handleChange}
            required
          />

          {/* Confirm Password Field */}
          <label>Confirm Password</label>
          <input
            type="password"
            name="confirmPassword"
            value={form.confirmPassword}
            onChange={handleChange}
            required
          />

          {/* Display validation or API error */}
          {error && <p className={styles.error}>{error}</p>}

          {/* Form Buttons */}
          <div className={styles.btnRow}>
            {/* Cancel Button */}
            <button
              type="button"
              className={styles.cancelBtn}
              onClick={handleCancel}
            >
              Cancel
            </button>

            {/* Submit Button */}
            <button type="submit" className={styles.saveBtn}>
              Create Admin
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
