// References:
// React useEffect: https://react.dev/reference/react/useEffect
// React useState: https://react.dev/reference/react/useState
// Axios Instances: https://axios-http.com/docs/instance


// Import React hooks for managing state and performing side effects
import { useEffect, useState } from "react";

// Import API call that fetches dashboard summary data from backend
import { getDashboardSummary } from "../api/adminDashboard";

// Import CSS
import styles from "./AdminDashboard.module.css";

export default function AdminDashboard() {
  // React state to store summary data returned from backend
  const [summary, setSummary] = useState(null);

  /**
   * useEffect runs after the component renders.
   * Used for fetching dashboard summary only once on initial load.
   */
  useEffect(() => {
    async function loadSummary() {
      const data = await getDashboardSummary();
      setSummary(data); // Update state with fetched summary data
    }
    loadSummary();
  }, []);

  // While data is loading, show a placeholder
  if (!summary) return <p>Loading dashboard...</p>;

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>Dashboard Summary</h2>

      {/* Responsive grid layout for summary cards */}
      <div className={styles.row}>

        {/* Total Animals Card */}
        <div className={styles.card}>
          <h3>Total Animals</h3>
          <p>{summary.total_animals}</p>
        </div>

        {/* Pending Applications Card */}
        <div className={styles.card}>
          <h3>Pending Applications</h3>
          <p>{summary.total_pending_applications}</p>
        </div>

        {/* Approved Applications Card */}
        <div className={styles.card}>
          <h3>Approved Applications</h3>
          <p>{summary.total_approved_applications}</p>
        </div>

        {/* Rejected Applications Card */}
        <div className={styles.card}>
          <h3>Rejected Applications</h3>
          <p>{summary.total_rejected_applications}</p>
        </div>
      </div>

      {/* Total Adopters Card */}
      <div className={styles.row}>
        <div className={styles.card}>
          <h3>Total Adopters</h3>
          <p>{summary.total_adopters}</p>
        </div>

        <div className={styles.card}>
          <h3>Total Admins</h3>
          <p>{summary.total_admins}</p>
        </div>
      </div>
    </div>
  );
}
