// References:
// useNavigate: https://reactrouter.com/en/main/hooks/use-navigate
// useParams: https://reactrouter.com/en/main/hooks/use-params
// useEffect: https://react.dev/reference/react/useEffect
// useState: https://react.dev/reference/react/useState
// Handling forms in React: https://react.dev/learn/sharing-state-between-components


import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getAdminById, updateAdmin } from "../api/users";
import styles from "../styles/AdminUserUpdate.module.css";

export default function AdminUserUpdate() {
  const navigate = useNavigate(); // Used to redirect
  const { userId } = useParams(); // Get admin ID from URL

  // Form state to store editable fields
  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    password: "",
    confirmPassword: "",
  });

  const [error, setError] = useState(""); // Display password mismatch or API errors

  // Load admin data when page loads
  useEffect(() => {
    async function load() {
      const data = await getAdminById(userId); // Fetch admin info from backend

      // fill form with existing data
      setForm({
        name: data.name || "",
        email: data.email || "",
        phone: data.phone || "",
        address: data.address || "",
        password: "",
        confirmPassword: "",
      });
    }

    load();
  }, [userId]);

  // Update form state on input change
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  // Cancel button
  const handleCancel = () => {
    navigate("/admin/users");
  };

  // Submit update request
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    // Password and confirmation must match
    if (form.password !== form.confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    // Build request payload
    const payload = {
      name: form.name,
      email: form.email,
      phone: form.phone,
      address: form.address,
    };

    // Only send password if the user typed something
    if (form.password) {
      payload.password = form.password;
    }

    try {
      await updateAdmin(userId, payload); // Send update request to backend
      alert("Admin updated successfully!");
      navigate("/admin/users"); // Redirect back to admin list
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.detail || "Failed to update admin.");
    }
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <div className={styles.innerBox}>
        <h2 className={styles.title}>Update Admin</h2>

        <form className={styles.form} onSubmit={handleSubmit}>

          {/* Name */}
          <label>Name</label>
          <input
            name="name"
            value={form.name}
            onChange={handleChange}
            required
          />

          {/* Email */}
          <label>Email</label>
          <input
            name="email"
            value={form.email}
            onChange={handleChange}
            required
          />

          {/* Phone */}
          <label>Phone</label>
          <input
            name="phone"
            value={form.phone}
            onChange={handleChange}
            required
          />

          {/* Address */}
          <label>Address</label>
          <input
            name="address"
            value={form.address}
            onChange={handleChange}
            required
          />

          {/* Password */}
          <label>New Password (optional)</label>
          <input
            type="password"
            name="password"
            value={form.password}
            onChange={handleChange}
          />

          {/* Confirm Password */}
          <label>Confirm Password</label>
          <input
            type="password"
            name="confirmPassword"
            value={form.confirmPassword}
            onChange={handleChange}
          />

          {/* Error message */}
          {error && <p className={styles.error}>{error}</p>}

          {/* Buttons row */}
          <div className={styles.buttonRow}>
            <button className={styles.saveBtn}>Update Admin</button>

            <button
              type="button"
              className={styles.cancelBtn}
              onClick={handleCancel}
            >
              Cancel
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
