// References:
// React useState: https://react.dev/reference/react/useState
// React useEffect: https://react.dev/reference/react/useEffect
// Debouncing: https://dev.to/manishkc104/debounce-input-in-react-3726

import { useEffect, useState } from "react";
import { getAdopters } from "../api/user";
import styles from "./AdminAdopters.module.css";

export default function AdminAdopters() {
  // Store the list of adopters from backend
  const [adopters, setAdopters] = useState([]);

  // Pagination states
  const [page, setPage] = useState(1);
  const [limit] = useState(10);
  const [totalPages, setTotalPages] = useState(1);

  // Search input states
  const [searchInput, setSearchInput] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");

  // search input:
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(searchInput); // update real search value
      setPage(1); // reset to first page when searching
    }, 500);

    // Cleanup function to clear timeout when input changes
    return () => clearTimeout(timer);

  }, [searchInput]); // runs every time searchInput changes

  // Load adopters when page or search changes
  useEffect(() => {
    loadAdopters();
  }, [page, debouncedSearch]);

  // Fetch adopters from backend API
  async function loadAdopters() {
    try {
      const params = {
        page,
        limit,
        search: debouncedSearch || undefined,
      };

      // API response
      const data = await getAdopters(params);

      setAdopters(data.users || []);
      setTotalPages(data.total_pages || 1);
    } catch (err) {
      console.error("Failed to load adopters:", err);
    }
  }

  // Reset all filters
  const clearFilters = () => {
    setSearchInput("");
    setDebouncedSearch("");
    setPage(1);
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>Adopters Management</h2>

      {/* Search & Filter Section */}
      <div className={styles.filters}>
        {/* Search bar */}
        <input
          type="text"
          placeholder="Search by name, email or address"
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
        />

        {/* Clear filters button */}
        <button className={styles.clearBtn} onClick={clearFilters}>
          Clear Filters
        </button>

      </div>

      {/* Table Section */}
      <div className={styles.tableWrapper}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Joined At</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {adopters.map((u) => (
              <tr key={u.id}>
                <td>{u.name}</td>
                <td>{u.email}</td>
                <td>{u.phone}</td>
                <td>{u.address}</td>
                <td>{new Date(u.created_at).toLocaleDateString()}</td>

                {/* Action column */}
                <td className={styles.actions}>
                  <button className={styles.deleteBtn}>
                    Delete
                  </button>
                </td>

              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination Section */}
      <div className={styles.pagination}>
        {/* Previous Page */}
        <button disabled={page === 1} onClick={() => setPage(page - 1)}>
          Prev
        </button>

        {/* Page Info */}
        <span>
          Page {page} of {totalPages}
        </span>

        {/* Next Page */}
        <button
          disabled={page === totalPages}
          onClick={() => setPage(page + 1)}
        >
          Next
        </button>
      </div>
    </div>
  );
}
