// References:
// https://react.dev/reference/react/useState
// https://react.dev/learn/sharing-state-between-components#reacting-to-input-with-state
// https://reactrouter.com/en/main/start/tutorial#handling-form-submissions
// https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage


// React hook for managing component state
import { useState } from "react"; 

// API function for sending admin login request
import { adminLogin } from "../api/admin_auth"; 

// CSS Module for styling this page
import styles from "./AdminLogin.module.css"; 

// Hook for programmatic navigation
import { useNavigate } from "react-router-dom";


export default function AdminLoginPage() {
  const navigate = useNavigate(); 

  // Form state to store email + password input values
  const [form, setForm] = useState({
    email: "",
    password: "",
  });

  // Error message shown if login fails
  const [error, setError] = useState("");

  // Handle input changes
  const handleChange = (e) => {
    setForm({
      ...form,                 // copy existing form values
      [e.target.name]: e.target.value,  // update only the changed field
    });
  };


  // Handle login form submission
  const handleSubmit = async (e) => {
    e.preventDefault(); // prevent page refresh
    setError("");       // reset error state

    try {
      // Call backend login API
      const { access_token } = await adminLogin(form);

      // Store admin JWT token separately from adopter token
      localStorage.setItem("adminToken", access_token);

      // Redirect to admin dashboard
      navigate("/admin/dashboard");

    } catch (err) {
      // Show backend error message or fallback message
      setError(err.response?.data?.detail || "Login failed");
    }
  };


  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>Admin Login</h2>

      {/* Login form */}
      <form className={styles.form} onSubmit={handleSubmit}>

        <label>Email</label>
        <input
          type="email"
          name="email"
          value={form.email}
          onChange={handleChange}
        />

        <label>Password</label>
        <input
          type="password"
          name="password"
          value={form.password}
          onChange={handleChange}
        />

        {/* Show error message if login failed */}
        {error && <p className={styles.error}>{error}</p>}

        <button className={styles.loginBtn}>Login</button>
      </form>
    </div>
  );
}
