// References:
// https://vitejs.dev/guide/features.html#css-modules
// https://react.dev/reference/react/useEffect


// Import React hooks for state management and side effects
import { useEffect, useState } from "react";

// Import API functions for fetching and updating adopter data
import { getCurrentUser, updateAdopterProfile } from "../api/users";

// Import CSS module for scoped styling
import styles from "../styles/AdopterProfile.module.css";

export default function AdopterProfile() {

  // Store the original user data to detect changes later
  const [original, setOriginal] = useState(null);

  // Form state for editable fields
  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    password: "",
    confirmPassword: ""
  });

  // Store the user ID for update requests
  const [userId, setUserId] = useState(null);

  // to check if any field has been changed
  const [isDirty, setIsDirty] = useState(false);

  // Error message for password mismatch
  const [passwordError, setPasswordError] = useState("");

  // Load current user info on mount
  useEffect(() => {
    async function loadUser() {
      const user = await getCurrentUser(); // Fetch logged-in user

      setUserId(user.id);

      // Prepare the initial dataset
      const initial = {
        name: user.name || "",
        email: user.email || "",
        phone: user.phone || "",
        address: user.address || "",
      };

      setOriginal(initial);                 // Save original values
      setForm({ ...initial, password: "", confirmPassword: "" }); // Populate form
    }

    loadUser();
  }, []);

  // Detect if the form has unsaved changes
  useEffect(() => {
    if (!original) return;

    // Check if any field differs from original
    const hasChanges =
      form.name !== original.name ||
      form.email !== original.email ||
      form.phone !== original.phone ||
      form.address !== original.address ||
      form.password.length > 0 ||
      form.confirmPassword.length > 0;

    setIsDirty(hasChanges); // Enable/disable Save button
  }, [form, original]); // Runs whenever form or original changes

  // Ref: https://react.dev/learn/sharing-state-between-components#updating-objects-in-state
  // Handle input changes for all form fields
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value, // Update based on input's name attribute
    });
  };

  // Ref: https://react.dev/reference/react-dom/components/form#onsubmit
  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault(); // Prevent page reload

    // Validate password match before sending request
    if (form.password !== form.confirmPassword) {
      setPasswordError("Passwords do not match");
      return;
    }

    setPasswordError("");

    // Prepare payload for API
    const payload = {
      name: form.name,
      email: form.email,
      phone: form.phone,
      address: form.address,
    };

    // Only include password if user typed a new one
    if (form.password) {
      payload.password = form.password;
    }

    // API call to update adopter profile
    await updateAdopterProfile(userId, payload);

    alert("Profile updated successfully!");

    // Refresh original data and clear password fields
    const updatedOriginal = {
      name: form.name,
      email: form.email,
      phone: form.phone,
      address: form.address
    };

    setOriginal(updatedOriginal);

    setForm({
      ...updatedOriginal,
      password: "",
      confirmPassword: ""
    });
  };

  // Show loading until data is fetched
  if (!original) return <p>Loading...</p>;

  // Render profile
  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2>My Profile</h2>

      <form className={styles.form} onSubmit={handleSubmit}>
        
        {/* Name */}
        <label>Name</label>
        <input 
          type="text"
          name="name"
          value={form.name}
          onChange={handleChange}
        />

        {/* Email */}
        <label>Email</label>
        <input 
          type="email"
          name="email"
          value={form.email}
          onChange={handleChange}
        />

        {/* Phone */}
        <label>Phone</label>
        <input 
          type="text"
          name="phone"
          value={form.phone}
          onChange={handleChange}
        />

        {/* Address */}
        <label>Address</label>
        <input 
          type="text"
          name="address"
          value={form.address}
          onChange={handleChange}
        />

        {/* Password */}
        <label>New Password (optional)</label>
        <input 
          type="password"
          name="password"
          value={form.password}
          onChange={handleChange}
          placeholder="Enter new password"
        />

        {/* Confirm Password */}
        <label>Confirm New Password</label>
        <input 
          type="password"
          name="confirmPassword"
          value={form.confirmPassword}
          onChange={handleChange}
          placeholder="Re-enter new password"
        />

        {/* Password error message */}
        {passwordError && <p className={styles.error}>{passwordError}</p>}

        {/* Save button disabled until form is changed */}
        <button 
          className={styles.saveBtn} 
          type="submit"
          disabled={!isDirty}
        >
          Save Changes
        </button>
      </form>
    </div>
  );
}
