// References:
// https://api.reactrouter.com/v7/functions/react_router.useParams.html
// https://api.reactrouter.com/v7/functions/react_router.useNavigate.html
// https://react.dev/learn/responding-to-events#handling-form-submission
// https://react.dev/learn/conditional-rendering


import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { submitApplication } from "../api/applications"; // API call for submitting an application
import { getAnimalById } from "../api/animals"; // API call for fetching a single animal
import styles from "../styles/AdoptionForm.module.css"; // CSS module for styling

export default function AdoptionForm() {

  // Extract :animalId from the URL
  const { animalId } = useParams();

  // React Router hook to redirect user
  const navigate = useNavigate();

  // State to store the fetched animal data
  const [animal, setAnimal] = useState(null);

  // Reason input value
  const [reason, setReason] = useState("");

  // Error message from backend
  const [error, setError] = useState("");

  // Success message after submission
  const [success, setSuccess] = useState("");

  // Load API base URL from .env
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Fetch the animal details when the component loads
  useEffect(() => {
    const fetchAnimal = async () => {
      try {
        // Call backend to get animal by ID
        const data = await getAnimalById(animalId);
        setAnimal(data); // Save animal data in state
      } catch (err) {
        // If API fails
        setError("Failed to load animal information.");
      }
    };

    fetchAnimal();
  }, [animalId]); // Re-run if animalId changes


  // Handle adoption form submission
  const handleSubmit = async (e) => {
    e.preventDefault(); // Prevent page reload
    setError("");       // Clear previous error message

    try {
      // Submit adoption application
      const res = await submitApplication({
        animal_id: Number(animalId),
        reason: reason,
      });

      // Show success message
      setSuccess("Application submitted successfully!");

      // Redirect user after short delay
      setTimeout(() => navigate("/"), 500);

    } catch (err) {
      // Extract backend error message
      const msg = err.response?.data?.detail || "Submission failed";
      setError(msg);
    }
  };

  // Show loading text while fetching animal
  if (!animal) {
    return <p className={styles.loading}>Loading...</p>;
  }

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <button onClick={() => navigate(-1)}>
          ← Back
      </button>
      <h2 className={styles.title}>Adoption Application</h2>

      {/* Display basic animal info above the form */}
      <div className={styles.animalInfo}>
        <img
          src={`${BASE_URL}${animal.photo_url}`}
          alt={animal.name}
          className={styles.image}
        />

        <div>
          <h3>{animal.name}</h3>
          <p><strong>Breed:</strong> {animal.breed}</p>
          <p><strong>Age:</strong> {animal.age}</p>
          <p><strong>Status:</strong> {animal.adoption_status}</p>
        </div>
      </div>

      {/* Error message from backend */}
      {error && <p className={styles.error}>{error}</p>}

      {/* Success message after submission */}
      {success && <p className={styles.success}>{success}</p>}

      {/* Adoption form */}
      <form onSubmit={handleSubmit} className={styles.form}>
        <label className={styles.label}>
          Why do you want to adopt this animal?
        </label>

        {/* Textarea input bound to reason state */}
        <textarea
          className={styles.textarea}
          value={reason}
          onChange={(e) => setReason(e.target.value)}
          required
        />

        {/* Submit button */}
        <button type="submit" className={styles.submitButton}>
          Submit Application
        </button>
      </form>
    </div>
  );
}
