// References:
// useState: https://react.dev/reference/react/useState
// Forms: https://www.w3schools.com/react/react_forms.asp
// useNavigate: https://reactrouter.com/en/main/hooks/use-navigate
// Link: https://reactrouter.com/en/main/components/link
// POST request: https://axios-http.com/docs/post_example


// React imports for managing component state
import { useState } from "react";

// React Router imports for navigation + linking between pages
import { Link, useNavigate } from "react-router-dom";

// Custom API function to call backend registration endpoint
import { registerAdopter } from "../api/users";

// Import CSS module for styling
import styles from "../styles/AdopterRegister.module.css";

export default function RegisterPage() {

  const navigate = useNavigate();

  // Store all form fields inside a single object
  const [form, setForm] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    password: "",
    confirmPassword: "",
  });

  // Error and success messages for user feedback
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  // Update form values dynamically based on input name attribute
  const handleChange = (e) => {
    // Copy old values and update the field that changed
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  // Handle registration form submission
  const handleSubmit = async (e) => {
    // Prevent the page from refreshing
    e.preventDefault();

    // validation for matching passwords
    if (form.password !== form.confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    try {
      // Clear any previous error
      setError("");

      // payload for backend request
      const payload = {
        name: form.name,
        email: form.email,
        phone: form.phone,
        address: form.address,
        password: form.password,
      };

      // Send POST request to backend
      await registerAdopter(payload);

      // Show success message and redirect the user to login page
      setSuccess("Account created successfully! Redirecting to login...");

      // Delay redirect so user can read success message
      setTimeout(() => navigate("/login"), 1000);

    } catch (err) {
        // Show error message
      setError("Failed to create account. Email may already be in use.");
    }
  };

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2 className={styles.title}>Create Account</h2>

      {/* Display error or success message */}
      {error && <p className={styles.error}>{error}</p>}
      {success && <p className={styles.success}>{success}</p>}

      {/* Registration form */}
      <form onSubmit={handleSubmit}>
        
        {/* Username */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Username</label>
          <input
            type="text"
            className={styles.input}
            name="name"
            value={form.name}
            onChange={handleChange}
            required
          />
        </div>

        {/* Email */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Email</label>
          <input
            type="email"
            className={styles.input}
            name="email"
            value={form.email}
            onChange={handleChange}
            required
          />
        </div>

        {/* Phone */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Phone</label>
          <input
            type="text"
            className={styles.input}
            name="phone"
            value={form.phone}
            onChange={handleChange}
            required
          />
        </div>

        {/* Address */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Address</label>
          <input
            type="text"
            className={styles.input}
            name="address"
            value={form.address}
            onChange={handleChange}
            required
          />
        </div>

        {/* Password */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Password</label>
          <input
            type="password"
            className={styles.input}
            name="password"
            value={form.password}
            onChange={handleChange}
            required
          />
        </div>

        {/* Confirm Password */}
        <div className={styles.formGroup}>
          <label className={styles.label}>Confirm Password</label>
          <input
            type="password"
            className={styles.input}
            name="confirmPassword"
            value={form.confirmPassword}
            onChange={handleChange}
            required
          />
        </div>

        {/* Submit button */}
        <button className={styles.button}>Create Account</button>

        {/* Link to Login Page */}
        <p className={styles.loginText}>
          Already have an account?{" "}
          <Link to="/login" className={styles.loginLink}>
            Login
          </Link>
        </p>
      </form>
    </div>
  );
}
