// References:
// React useState: https://react.dev/reference/react/useState
// React useEffect: https://react.dev/reference/react/useEffect
// Environment Variables in Vite: https://vite.dev/guide/env-and-mode.html


import { useEffect, useState } from "react";
import { getAnimals } from "../api/animals";
import styles from "./AnimalsList.module.css";

export default function AnimalsList() {
  // Store list of animals
  const [animals, setAnimals] = useState([]);

  // Pagination state
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  // Loading indicator
  const [loading, setLoading] = useState(true);

  // Load API base URL from .env
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Fetch animals when page changes
  useEffect(() => {
    async function fetchAnimalData() {
      try {
        setLoading(true);

        // Call backend API
        const data = await getAnimals(page);

        // Update animals list + total pages
        setAnimals(data.data.animals);
        setTotalPages(data.total_pages);
      } catch (err) {
        console.error("Error fetching animals:", err);
      } finally {
        setLoading(false);
      }
    }

    fetchAnimalData();
  }, [page]);

  // Show loading message while data is fetching
  if (loading) {
    return <div className={styles.loading}>Loading animals...</div>;
  }

  return (
    <div className={styles.container}>

      {/* The UI layout & form structure below is generated by ChatGPT */}

      {/* Page Title */}
      <h2 className={styles.pageTitle}>Available Animals for Adoption</h2>

      {/* Animals Grid */}
      <div className={styles.grid}>
        {animals.map((animal) => (
          <div key={animal.id} className={styles.card}>
            {/* Animal Photo */}
            <img
              src={`${BASE_URL}${animal.photo_url}`}
              alt={animal.name}
              className={styles.photo}
            />

            {/* Animal Name */}
            <h3 className={styles.name}>{animal.name}</h3>

            {/* Species + Breed */}
            <p className={styles.species}>
              {animal.species} • {animal.breed}
            </p>

            {/* Age */}
            <p className={styles.age}>Age: {animal.age}</p>

            {/* Adoption Status */}
            <span
              className={
                animal.adoption_status === "AVAILABLE"
                  ? styles.statusAvailable
                  : styles.statusAdopted
              }
            >
              {animal.adoption_status}
            </span>
          </div>
        ))}
      </div>

      {/* Pagination Buttons */}
      <div className={styles.paginationContainer}>
        <button
          className={styles.paginationButton}
          onClick={() => setPage((p) => p - 1)}
          disabled={page === 1}
        >
          Prev
        </button>

        <span className={styles.paginationText}>
          {page} / {totalPages}
        </span>

        <button
          className={styles.paginationButton}
          onClick={() => setPage((p) => p + 1)}
          disabled={page === totalPages}
        >
          Next
        </button>
      </div>
    </div>
  );
}
