// References:
// React useState: https://react.dev/reference/react/useState
// React useEffect: https://react.dev/reference/react/useEffect
// Cleanup function: https://react.dev/reference/react/useEffect#examples-cleaning-up-a-subscription
// Environment Variables in Vite: https://vite.dev/guide/env-and-mode.html
// MDN setTimeout: https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout
// Using a Timeout Inside useEffect: https://react.dev/reference/react/useEffect#fetching-data-with-effects
// React Router useNavigate: https://api.reactrouter.com/v7/functions/react_router.useNavigate.html


import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getAnimals } from "../api/animals";
import styles from "./AnimalsList.module.css";

export default function AnimalsList() {
  // Nvaigation hook
  const navigate = useNavigate();

  // Store list of animals
  const [animals, setAnimals] = useState([]);

  // Pagination state
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  // Filters
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [gender, setGender] = useState("");
  const [adoptionStatus, setAdoptionStatus] = useState("");

  // Loading indicator
  const [loading, setLoading] = useState(true);

  // Load API base URL from .env
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Debounce the search input (wait 500ms after user stops typing)
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1); // Reset to first page when search changes
    }, 500); // 500ms delay

    return () => clearTimeout(timer); // Cleanup on each keystroke
  }, [search]);

  // Fetch animals whenever filters or page changes
  useEffect(() => {
    async function fetchAnimalData() {
      try {
        setLoading(true);

        // Call backend API with filters
        const data = await getAnimals(page, 12, debouncedSearch, gender, adoptionStatus);

        if (!data || !data.data) return;

        // Update animals list + total pages
        setAnimals(data.data.animals);
        setTotalPages(data.data.total_pages);
      } catch (err) {
        console.error("Error fetching animals:", err);
      } finally {
        setLoading(false);
      }
    }

    fetchAnimalData();
  }, [page, debouncedSearch, gender, adoptionStatus]);

  // Reset all filters
  const clearFilters = () => {
    setSearch("");
    setDebouncedSearch("");
    setGender("");
    setAdoptionStatus("");
    setPage(1);
  };

  // Show loading screen while fetching data
  return (

    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2 className={styles.pageTitle}>Available Animals for Adoption</h2>

      {/* search & filter section */}
      <div className={styles.filterBar}>
        {/* Search by name/species/breed */}
        <input
          type="text"
          className={styles.searchInput}
          placeholder="Search by name, species, or breed..."
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
          }}
        />

        {/* Gender Filter */}
        <select
          className={styles.select}
          value={gender}
          onChange={(e) => {
            setGender(e.target.value);
            setPage(1);
          }}
        >
          <option value="">All Genders</option>
          <option value="Male">Male</option>
          <option value="Female">Female</option>
        </select>

        {/* Adoption Status Filter */}
        <select
          className={styles.select}
          value={adoptionStatus}
          onChange={(e) => {
            setAdoptionStatus(e.target.value);
            setPage(1);
          }}
        >
          <option value="">All Status</option>
          <option value="Available">Available</option>
          <option value="Adopted">Adopted</option>
        </select>

        {/* Clear Filters */}
        <button
          className={styles.clearButton}
          onClick={clearFilters}
        >
          Clear Filters
        </button>
      </div>

      {/* animal grid section */}
      {loading ? (
        <div className={styles.loading}>Loading animals...</div>
      ) : (
        <div className={styles.grid}>
          {animals.length === 0 ? (
            <p>No animals found.</p>
          ) : (
            animals.map((animal) => (
              <div key={animal.id} className={styles.card} onClick={() => navigate(`/animals/${animal.id}`)}>
                {/* Animal Photo */}
                <img
                  src={`${BASE_URL}${animal.photo_url}`}
                  alt={animal.name}
                  className={styles.photo}
                />

                {/* Name */}
                <h3 className={styles.name}>{animal.name}</h3>

                {/* Species & Breed */}
                <p className={styles.species}>
                  {animal.species} • {animal.breed}
                </p>

                {/* Age */}
                <p className={styles.age}>Age: {animal.age}</p>

                {/* Adoption Status */}
                <span
                  className={
                    animal.adoption_status === "AVAILABLE"
                      ? styles.statusAvailable
                      : styles.statusAdopted
                  }
                >
                  {animal.adoption_status}
                </span>
              </div>
            ))
          )}
        </div>
      )}

      {/* pagination section */}
      <div className={styles.paginationContainer}>
        <button
          className={styles.paginationButton}
          onClick={() => setPage((p) => p - 1)}
          disabled={page === 1}
        >
          Prev
        </button>

        <span className={styles.paginationText}>
          {page} / {totalPages}
        </span>

        <button
          className={styles.paginationButton}
          onClick={() => setPage((p) => p + 1)}
          disabled={page === totalPages}
        >
          Next
        </button>
      </div>
    </div>
  );
}
