// References:
// https://reactrouter.com/en/main/hooks/use-params
// https://reactrouter.com/en/main/hooks/use-navigate
// https://react.dev/reference/react/useState
// https://react.dev/reference/react/useEffect
// https://react.dev/learn/updating-objects-in-state
// https://react.dev/learn/managing-state
// https://react.dev/reference/react/useEffect#fetching-data-with-effects


import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  getApplicationById,
  updateApplicationByAdopter,
} from "../api/applications";
import styles from "../styles/ApplicationDetails.module.css";

export default function ApplicationDetails() {

  // Extract applicationId from URL parameters
  const { applicationId } = useParams();

  // React Router navigation hook
  const navigate = useNavigate();

  // Component State Management
  const [application, setApplication] = useState(null);  // Full application data
  const [loading, setLoading] = useState(true);           // Loading indicator
  const [isEditing, setIsEditing] = useState(false);      // Edit mode state
  const [updatedReason, setUpdatedReason] = useState(""); // User reason editing
  const [error, setError] = useState("");                 // Error message
  const [success, setSuccess] = useState("");             // Success state

  // Load API Base URL from Vite environment
  const BASE_URL = import.meta.env.VITE_API_BASE_URL;

  // Fetch application details on first render
  useEffect(() => {
    const load = async () => {
      try {
        // Call backend API to fetch application details
        const data = await getApplicationById(applicationId);
        setApplication(data);

        // reason for editing
        setUpdatedReason(data.reason);
      } catch (err) {
        setError("Failed to load application");
      } finally {
        setLoading(false); // Hide loading state
      }
    };

    load();
  }, [applicationId]); // Run again if ID changes in URL

  // FUNCTION: Update application reason
  const handleUpdate = async () => {
    try {
      setError("");

      await updateApplicationByAdopter(applicationId, {
        reason: updatedReason,
      });

      setSuccess("Application updated successfully.");
      setIsEditing(false);

      // Reload updated data
      const fresh = await getApplicationById(applicationId);
      setApplication(fresh);

    } catch (err) {
      setError(err.response?.data?.detail || "Failed to update.");
    }
  };

  // FUNCTION: Cancel application
  const handleCancel = async () => {
    try {
      setError("");

      await updateApplicationByAdopter(applicationId, {
        application_status: "Cancelled",
      });

      setSuccess("Application has been cancelled.");

      // Reload updated data
      const fresh = await getApplicationById(applicationId);
      setApplication(fresh);

    } catch (err) {
      setError(err.response?.data?.detail || "Failed to cancel application.");
    }
  };

  // Loading and Not Found States
  if (loading) return <p className={styles.loading}>Loading...</p>;
  if (!application) return <p className={styles.notFound}>Application not found.</p>;

  // Determine if user is allowed to edit
  // User CANNOT edit if Admin already approved/rejected/cancelled
  const canEdit =
    application.status !== "Approved" &&
    application.status !== "Rejected" &&
    application.status !== "Cancelled";

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.page}>

      <button className={styles.backBtn} onClick={() => navigate(-1)}>
        ← Back
      </button>

      <h1 className={styles.title}>Application Details</h1>

      <div className={styles.card}>
        
        {/* left side */}
        <div className={styles.imageSection}>
          <img
            // Full image URL = BASE_URL + photo path stored in DB
            src={`${BASE_URL}${application.photo_url}`}
            alt={application.animal_name}
            className={styles.image}
          />
        </div>

        {/* right side */}
        <div className={styles.detailsSection}>
          <span className={`${styles.statusBadge} ${styles[application.status]}`}>
            {application.status}
          </span>

          {/* Animal Info */}
          <div className={styles.block}>
            <h3>Animal Information</h3>
            <p><strong>Name:</strong> {application.animal_name}</p>
            <p><strong>Animal ID:</strong> {application.animal_id}</p>
          </div>

          <div className={styles.block}>
            <h3>Application Info</h3>
            <p>
              <strong>Submitted:</strong>{" "}
              {new Date(application.created_at).toLocaleString()}
            </p>
            <p>
              <strong>Last Updated:</strong>{" "}
              {new Date(application.updated_at).toLocaleString()}
            </p>
          </div>

          <div className={styles.block}>
            <h3>Your Reason</h3>

            {/* VIEW MODE */}
            {!isEditing ? (
              <>
                <p className={styles.reasonText}>{application.reason}</p>

                {canEdit && (
                  <button
                    className={styles.editBtn}
                    onClick={() => setIsEditing(true)}
                  >
                    Edit Reason
                  </button>
                )}
              </>
            ) : (
              <>
                <textarea
                  className={styles.textarea}
                  value={updatedReason}
                  onChange={(e) => setUpdatedReason(e.target.value)}
                />

                {/* Edit action buttons */}
                <div className={styles.editActions}>
                  <button
                    className={styles.saveBtn}
                    onClick={handleUpdate}
                  >
                    Save
                  </button>

                  <button
                    className={styles.cancelEditBtn}
                    onClick={() => setIsEditing(false)}
                  >
                    Cancel
                  </button>
                </div>
              </>
            )}
          </div>

          {/* Cancel Application Button*/}
          {canEdit && (
            <button
              className={styles.cancelAppBtn}
              onClick={handleCancel}
            >
              Cancel Application
            </button>
          )}

        </div>
      </div>
    </div>
  );
}
