// References:
// React useState: https://react.dev/reference/react/useState
// React useEffect: https://react.dev/reference/react/useEffect
// Conditional Rendering: https://react.dev/learn/conditional-rendering
// Rendering Lists: https://react.dev/learn/rendering-lists
// Date formatting: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString


import { useEffect, useState } from "react";
import { getMyApplications } from "../api/applications"; 
import styles from "../styles/ApplicationsList.module.css"; // CSS module import

export default function ApplicationsList() {

  // Store list of applications from backend
  const [applications, setApplications] = useState([]);

  // Controls loading state for UI feedback
  const [loading, setLoading] = useState(true);

  // Runs once when the component is mounted
  useEffect(() => {
    // Fetch adoption applications for the current logged-in user
    const fetchData = async () => {
      try {
        const apps = await getMyApplications(); // API call
        setApplications(apps); // Save applications to state
      } catch (err) {
        console.error("Error loading applications:", err);
      } finally {
        setLoading(false); // Stop loading spinner
      }
    };

    fetchData();
  }, []); // Empty dependency array

  // Show loading text while fetching applications
  if (loading) return <p className={styles.loading}>Loading...</p>;

  return (
    // The UI layout & form structure below is generated by ChatGPT
    <div className={styles.container}>
      <h2 className={styles.title}>My Adoption Applications</h2>

      {/* If no applications, show a message */}
      {applications.length === 0 && (
        <p className={styles.noData}>No applications found.</p>
      )}

      <div className={styles.list}>
        {/* Loop through all applications */}
        {applications.map((app) => (
          <div key={app.id} className={styles.card}>
            
            {/* Header section: Animal name + Application status */}
            <div className={styles.cardHeader}>
              <h3>{app.animal_name}</h3>

              {/* Dynamic status badge color: Submitted / Approved / Rejected */}
              <span className={`${styles.status} ${styles[app.status]}`}>
                {app.status}
              </span>
            </div>

            {/* Application reason */}
            <p>
              <strong>Reason:</strong> {app.reason}
            </p>

            {/* Created date formatted to readable format */}
            <p>
              <strong>Submitted at:</strong>{" "}
              {new Date(app.created_at).toLocaleString()}
            </p>

            {/* Navigate to Application Details page */}
            <button
              className={styles.detailsButton}
              onClick={() => window.location.href = `/#/applications/${app.id}`}
            >
              View Details
            </button>

          </div>
        ))}
      </div>
    </div>
  );
}
