// References:
// React Router: https://reactrouter.com/en/main/components/link
// React Router useNavigate: https://reactrouter.com/en/main/hooks/use-navigate
// localStorage docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage


import { Link, useNavigate } from "react-router-dom"; // React Router for navigation
import styles from "./AdminNavbar.module.css"; // CSS Module for styling

export default function AdminNavbar() {
    // useNavigate is used for redirecting
  const navigate = useNavigate(); 
  
  // Handle admin logout
  const handleLogout = () => {
    // Remove admin token from browser storage
    localStorage.removeItem("adminToken");

    // Redirect admin back to login page
    navigate("/admin/login", { replace: true });
  };

  return (
    // The UI layout below is generated by ChatGPT
    <nav className={styles.nav}>
      <div className={styles.leftArea}>
        <img src="/logo.png" alt="Logo" className={styles.logoImg} />
        <span className={styles.logoText}>Admin Dashboard</span>
      </div>

      <div className={styles.links}>
        {/* Link for navigation without page refresh */}
        <Link to="/admin/dashboard">Dashboard</Link>
        <Link to="/admin/animals">Animals</Link>
        <Link to="">Applications</Link>
        <Link to="">Adopters</Link>
        <Link to="">My Profile</Link>

        {/* Logout button */}
        <button className={styles.logoutBtn} onClick={handleLogout}>
          Logout
        </button>
      </div>
    </nav>
  );
}
